export enum RouterMap {
  // 主入口
  MAIN_ENTRY = 'MainEntry',

  SETTING_AGREEMENT = 'AgreementPage',

  USER_CUSTOM_SERVICE = 'CustomServicePage',
  USER_COLLECTION = 'MyCollectionPage',
  USER_VIEW_HISTORY = 'ViewHistoryPage',
  USER_POINTS_RECORD = 'PointsRecordPage',
  USER_REDEMPTION_SUBMIT = 'RedemptionSubmitPage',
  POINTS_MALL = 'PointsMallPage',
  USER_REDEMPTION_LIST = 'RedemptionListPage',
  USER_REDEMPTION_INFO = 'RedemptionInfoPage',
  PRODUCT_SWIPER = 'ProductSwiperPage',
  PRODUCT_REVIEW = 'ProductReviewPage',
  PRODUCT_SEARCH = 'ProductSearchPage',
  PRODUCT_SEARCH_RESULTS = 'ProductSearchResultsPage',
  PRODUCT_INFO = 'ProductInfoPage',
  PRODUCT_CATEGORY = 'CategoryPage',
  PRODUCT_SUBCATEGORY = 'SubCategoryPage',
  PRODUCT_CART = 'CartPage',
  PRODUCT_SECKILL = 'SeckillListPage',

  ORDER_SUBMIT = 'OrderSubmitPage',
  ORDER_SEARCH = 'OrderSearchPage',
  ORDER_LIST = 'OrderListPage',
  ORDER_INFO = 'OrderInfoPage',
  ORDER_EXPRESS_INFO = 'OrderExpressInfoPage',
  POINTS_EXPRESS_INFO = 'OrderExpressInfoPage',
  ORDER_REVIEW_CREATE = 'OrderReviewCreatePage',
  ORDER_REVIEW_INFO = 'OrderReviewInfoPage',
}
